"use client";

import {
  Container,
  Title,
  Text,
  Image,
  Stack,
  Badge,
  Group,
  Divider,
  TypographyStylesProvider,
  Skeleton,
  Button,
  Box,
  Paper,
} from "@mantine/core";
import { useGetJournalBySlugQuery } from "@/services/journalApi";

import {
  IconCalendar,
  IconUser,
  IconArrowLeft,
  IconHome,
} from "@tabler/icons-react";
import Link from "next/link";

interface JournalDetailClientProps {
  slug: string;
}

export default function JournalDetailClient({
  slug,
}: JournalDetailClientProps) {
  // 1. Fetch Journal Content
  const { data: journal, isLoading: journalLoading } =
    useGetJournalBySlugQuery(slug);

  if (journalLoading)
    return (
      <Container size="xl" py={100} px={{ base: 8, md: 12, lg: 16 }}>
        <Skeleton height={400} radius="md" />
      </Container>
    );

  if (!journal)
    return (
      <Container
        size="xl"
        py={100}
        ta="center"
        px={{ base: 8, md: 12, lg: 16 }}
      >
        <Title>Guide not found</Title>
      </Container>
    );

  return (
    <Container size="xl" py={80} px={{ base: 8, md: 12, lg: 16 }}>
      <Button
        component={Link}
        href="/journals"
        color="#4161df"
        variant="subtle"
        leftSection={<IconArrowLeft size={16} />}
        mb="xl"
      >
        Back to Insights
      </Button>

      <Stack gap="lg">
        <Badge size="lg" variant="filled" color="#4161df">
          {journal.category}
        </Badge>

        <Title order={1} size="42px" fw={900} style={{ lineHeight: 1.1 }}>
          {journal.title}
        </Title>

        <Group gap="xl" c="dimmed">
          <Group gap={5}>
            <IconCalendar size={18} />
            <Text size="sm">
              {new Date(journal.createdAt).toLocaleDateString("en-IN")}
            </Text>
          </Group>
          <Group gap={5}>
            <IconUser size={18} />
            <Text size="sm">PropertyBulbul Editorial</Text>
          </Group>
        </Group>

        <Image
          src={
            journal.coverImage ||
            "https://images.unsplash.com/photo-1590066305974-26999a08ec40?q=80&w=1200"
          }
          radius="md"
          alt={journal.title}
          h={200}
          w="100%"
        />

        {/* This renders the HTML generated by your AI */}
        <TypographyStylesProvider p={0} mt="xl">
          <div dangerouslySetInnerHTML={{ __html: journal.content }} />
        </TypographyStylesProvider>
      </Stack>
    </Container>
  );
}
